//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARBRAND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARBRAND()
        {
            this.MODELS = new HashSet<MODEL>();
        }
    
        public decimal brand_id { get; set; }
        public string car_name { get; set; }
        public string country { get; set; }
        public string url { get; set; }
        public Nullable<decimal> year_of_foundation { get; set; }
        public Nullable<decimal> income_bill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODEL> MODELS { get; set; }
    }
}
