//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsEntities : DbContext
    {
        public CarsEntities()
            : base("name=CarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARBRAND> CARBRANDS { get; set; }
        public virtual DbSet<EXTRA> EXTRAS { get; set; }
        public virtual DbSet<MODELEXTRASWITCHER> MODELEXTRASWITCHERs { get; set; }
        public virtual DbSet<MODEL> MODELS { get; set; }
    }
}
