//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELEXTRASWITCHER
    {
        public decimal msd_id { get; set; }
        public Nullable<decimal> extra_id { get; set; }
        public Nullable<decimal> model_id { get; set; }
    
        public virtual EXTRA EXTRA { get; set; }
        public virtual MODEL MODEL { get; set; }
    }
}
